### ISSUE TITLE
Add e2e test for update party policy

### ISSUE THREAD

**Issue by wgwz** [regen-network/registry-server#306]
This is to check that the login system, is working correctly with the RLS policies for updating parties/profiles.
We would like a e2e test to check the behavior for the edit profile story.
Currently we have a unit test that issues SQL for testing the policy.
We would like a more broad e2e test, since we are seeing a confusing behavior in the PR for this task:
https://github.com/regen-network/regen-registry/issues/1562

**Comment by blushi** [comment]
> We would like a more broad e2e test, since we are seeing a confusing behavior in the PR for this task:
> https://github.com/regen-network/regen-registry/issues/1562

what is this confusing behavior? 
on netlify deploy previews, I guess it might just be related to the session cookie not being set for now: https://github.com/regen-network/regen-web/pull/1819#issuecomment-1477450735
cc/ @flagrede @wgwz
